server:
  port: 3001
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/zoltannyaray/webrobot-config.git
          clone-on-start: true
  output:
    ansi:
      enabled: always